Gmaximum_ios = "15.1"

# Jailbreak Tools
JailbreakMap = [
    {
        "name": "checkra1n",
        "url": "https://checkra.in",
        "current_version": "0.12.2",
        "minimum_ios": "12.0",
        "minimum_pg": "5S",
        "maximum_ios": "14.8",
        "maximum_pg": "X",
        "type": "Semi-Tethered",
        "platforms": ['apple', 'linux'],
        "notes": ["A11 devices on iOS 14.0 and above require removing the passcode and enabling \"Skip A11 BPR check\" in the options.\nThis is not recommended, but it’s there."]
    },
    {
        "name": "Taurine",
        "url": "https://taurine.app",
        "current_version": "1.1.1",
        "minimum_ios": "14.0",
        "minimum_pg": "6S",
        "maximum_ios": "14.3",
        "maximum_pg": "12",
        "type": "Semi-Untethered",
        "platforms": ['apple']
    },
    {
        "name": "fugu14 for unc0ver",
        "url": "https://github.com/LinusHenze/Fugu14",
        "current_version": "1",
        "minimum_ios": "14.3",
        "maximum_ios": "14.5.1",
        "minimum_pg": "XS",
        "maximum_pg": "12 Pro",
        "type": "Near-Untethered",
        "platforms": ['apple'],
        "notes": ["It is an incomplete untethered jailbreak (so expect bugs). For now, it only supports arm64e devices. Visit r/jailbreak subreddit for more info and discussions."]
    },
    {
        "name": "unc0ver",
        "url": "https://unc0ver.dev",
        "current_version": "7.0.2",
        "minimum_ios": "11.0",
        "maximum_ios": "14.3",
        "minimum_pg": "5S",
        "maximum_pg": "12",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["A12 Supported between 12.0 - 12.3 and 12.4 - 12.4.1"]
    },
    {
        "name": "Odyssey",
        "url": "https://theodyssey.dev",
        "current_version": "1.3.3",
        "minimum_ios": "13.0",
        "maximum_ios": "13.7",
        "minimum_pg": "6S",
        "maximum_pg": "11",
        "type": "Semi-Untethered",
        "platforms": ['apple']
    },
    {
        "name": "Chimera",
        "url": "https://chimera.coolstar.org",
        "current_version": "1.6.4",
        "minimum_ios": "12.0",
        "maximum_ios": "12.5.5",
        "minimum_pg": "5S",
        "maximum_pg": "XS",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Works for; A7-A11 devices running 12.0-12.5.1, A12 devices on 12.0-12.1.2, and tvOS 12.0-12.2 and 12.4. (Nonce setter only on 12.1.3-12.2, 12.4-12.4.1 for A12 devices.)"]
    },
    {
        "name": "Electra",
        "url": "https://coolstar.org/electra/",
        "current_version": "2.0",
        "minimum_ios": "11.0",
        "maximum_ios": "11.4.1",
        "minimum_pg": "5S",
        "maximum_pg": "X",
        "type": "Semi-Untethered",
        "platforms": ['apple']
    },
    {
        "name": "TNS",
        "url": "https://totally-not.spyware.lol",
        "current_version": "1.14",
        "minimum_ios": "10.0",
        "maximum_ios": "10.3.3",
        "minimum_pg": "5S",
        "maximum_pg": "7",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 64-bit devices"]
    },
    {
        "name": "h3lix",
        "url": "https://h3lix.tihmstar.net/",
        "current_version": "RC 6",
        "minimum_ios": "10.0.1",
        "maximum_ios": "10.3.4",
        "minimum_pg": "5",
        "maximum_pg": "5",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 32-bit devices"]
    },
    {
        "name": "doubleh3lix",
        "url": "https://doubleh3lix.tihmstar.net",
        "current_version": "RC 8",
        "minimum_ios": "10.0.1",
        "maximum_ios": "10.3.3",
        "minimum_pg": "5S",
        "maximum_pg": "6S",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 64-bit devices", "iPhone 7/7 Plus excluded"]
    },
    {
        "name": "Meridian",
        "url": "https://meridian.sparkes.zone/",
        "current_version": "0.9-007",
        "minimum_ios": "10.0",
        "maximum_ios": "10.3.3",
        "minimum_pg": "5S",
        "maximum_pg": "7",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 64-bit devices"]
    },
    {
        "name": "yalu102",
        "url": "https://yalu.qwertyoruiop.com/",
        "current_version": "beta 7",
        "minimum_ios": "10.2",
        "maximum_ios": "10.2",
        "minimum_pg": "5S",
        "maximum_pg": "6S",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 64-bit devices", "iPhone 7/7 Plus excluded"]
    },
    {
        "name": "extra_recipe+yaluX",
        "url": "https://yalu.qwertyoruiop.com/",
        "current_version": "beta 4",
        "minimum_ios": "10.1.1",
        "maximum_ios": "10.0.1",
        "minimum_pg": "7",
        "maximum_pg": "7",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for the iPhone 7"]
    },
    {
        "name": "Pangu91",
        "url": "http://en.pangu.io/",
        "current_version": "1.3.2",
        "minimum_ios": "9.0",
        "maximum_ios": "9.1",
        "minimum_pg": "4S",
        "maximum_pg": "6S",
        "type": "Untethered",
        "platforms": ['windows', 'apple'],
        "notes": ["Official servers are down for this jailbreak."]
    },
    {
        "name": "Pangu933",
        "url": "http://en.pangu.io/",
        "current_version": "1.1",
        "minimum_ios": "9.2",
        "maximum_ios": "9.3.3",
        "minimum_pg": "5S",
        "maximum_pg": "6S",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Official servers are down for this jailbreak.", "Only for 64-bit devices", "Can be jumpstarted on-device via jbme.qwertyoruiop.com"]
    },
    {
        "name": "HomeDepot",
        "url": "http://wall.supplies/",
        "current_version": "RC3",
        "minimum_ios": "9.1",
        "maximum_ios": "9.3.4",
        "minimum_pg": "4S",
        "maximum_pg": "5",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 32-bit devices"]
    },
    {
        "name": "JailbreakMe4",
        "url": "http://jailbreak.me",
        "current_version": "4.0",
        "minimum_ios": "9.1",
        "maximum_ios": "9.3.4",
        "minimum_pg": "4S",
        "maximum_pg": "5",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 32-bit devices"]
    },
    {
        "name": "Phoenix",
        "url": "https://www.phoenixpwn.com",
        "current_version": "v6",
        "minimum_ios": "9.3.5",
        "maximum_ios": "9.3.6",
        "minimum_pg": "4S",
        "maximum_pg": "5",
        "type": "Semi-Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 32-bit devices"]
    },
    {
        "name": "TaiG",
        "url": "http://www.taig.com/en/",
        "current_version": "2.4.5",
        "minimum_ios": "8.0",
        "maximum_ios": "8.4",
        "minimum_pg": "4S",
        "maximum_pg": "6",
        "type": "Untethered",
        "platforms": ['windows', 'apple'],
        "notes": ["Official servers are down for this jailbreak."]
    },
    {
        "name": "Pangu8",
        "url": "http://en.8.pangu.io/",
        "current_version": "1.2.1",
        "minimum_ios": "8.0",
        "maximum_ios": "8.1",
        "minimum_pg": "4S",
        "maximum_pg": "6",
        "type": "Untethered",
        "platforms": ['windows', 'apple'],
        "notes": ["Official servers are down for this jailbreak."]
    },
    {
        "name": "etasonJB",
        "url": "http://tihmstar.net/etasonjb/",
        "current_version": "RC5",
        "minimum_ios": "8.4.1",
        "maximum_ios": "8.4.1",
        "minimum_pg": "4S",
        "maximum_pg": "5",
        "type": "Untethered",
        "platforms": ['apple'],
        "notes": ["Only for 32-bit devices"]
    },
    {
        "name": "HomeDepot841",
        "url": "http://wall.supplies/OLD%20iPhone%20HACKED.html",
        "current_version": "1.1 beta 1",
        "minimum_ios": "8.4.1",
        "maximum_ios": "8.4.1",
        "minimum_pg": "4S",
        "maximum_pg": "5",
        "type": "Semi-tethered",
        "platforms": ['apple'],
        "notes": ["Only for 32-bit devices", "Can be untethered by installing the etasonJB Untether package"]
    },
    {
        "name": "evasi0n7",
        "url": "http://evasi0n.com",
        "current_version": "1.0.7",
        "minimum_ios": "7.0",
        "maximum_ios": "7.0.6",
        "minimum_pg": "4",
        "maximum_pg": "5S",
        "type": "Untethered",
        "platforms": ['windows', 'apple'],
        "notes": ["Official servers are down for this jailbreak.", "evasi0n7 is known to cause bootloops with devices that were updated OTA."]
    },
    {
        "name": "Pangu",
        "url": "https://en.7.pangu.io",
        "current_version": "1.2.1",
        "minimum_ios": "7.1",
        "maximum_ios": "7.1.2",
        "minimum_pg": "4",
        "maximum_pg": "5S",
        "type": "Untethered",
        "platforms": ['windows', 'apple'],
        "notes": ["Official servers are down for this jailbreak."]
    },
    {
        "name": "evasi0n",
        "url": "http://evasi0n.com/iOS6",
        "current_version": "1.5.3",
        "minimum_ios": "6.0",
        "maximum_ios": "6.1.2",
        "minimum_pg": "3GS",
        "maximum_pg": "5",
        "type": "Untethered",
        "platforms": ['windows', 'apple']
    },
    {
        "name": "sn0wbreeze",
        "url": "https://ih8sn0w.com",
        "current_version": "2.9.14",
        "minimum_ios": "3.1.3",
        "maximum_ios": "6.1.3",
        "minimum_pg": "3GS",
        "maximum_pg": "4",
        "type": "Mixed",
        "platforms": ['windows'],
        "notes": ["iOS 6.1.3 on the iPhone 3GS (new bootrom) and iPhone 4 will be tethered."]
    },
    {
        "name": "p0sixspwn",
        "url": "https://ih8sn0w.com/p0sixspwn.html",
        "current_version": "1.0.8",
        "minimum_ios": "6.1.3",
        "maximum_ios": "6.1.6",
        "minimum_pg": "3GS",
        "maximum_pg": "5",
        "type": "Untethered",
        "platforms": ['windows', 'apple']
    }
]
